BBR2015/RestApi/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Database;
using Repository;

namespace RestApi.Controllers
{
    public class IndexController : Controller
    {
        private readonly OverridableSettings _settings;
        private readonly CurrentMatchProvider _currentMatchProvider;

        public IndexController(OverridableSettings settings, CurrentMatchProvider currentMatchProvider)
        {
            _settings = settings;
            _currentMatchProvider = currentMatchProvider;
        }

        // GET: Index
        public ActionResult Index()
        {
            var model = new IndexModel
            {
                TillatNyttLag = _settings.TillatOpprettNyttLag,
                TillatNySpiller = _settings.TillatOpprettNySpiller,
                MatchId = _currentMatchProvider.GetMatchId().ToString(),
                EksternInfoUrl = _settings.EksternInfoUrl,
                TestklientUrl = _settings.TestklientUrl
            };

            return View(model);
        }
    }

    public class IndexModel
    {
        
        public bool TillatNyttLag { get; set; }
        public bool TillatNySpiller { get; set; }
        
        public string MatchId { get; set; }
        public string EksternInfoUrl { get; set; }
        public string TestklientUrl { get; set; }
    }
}

BBR2015/RestApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>*@
                @Html.ActionLink("Bouvet Battle Royale", "Index", "Index", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; @DateTime.Now.Year - Bouvet</p>*@
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>